#!/usr/bin/env python

# Copyright 2020 Kent A. Vander Velden <kent.vandervelden@gmail.com>
#
# If you use this software, please consider contacting me. I'd like to hear
# about your work.
#
# This file is part of HAL-Chronos.
#
#     HAL-Chronos is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     HAL-Chronos is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with HAL-Chronos.  If not, see <https://www.gnu.org/licenses/>.

from __future__ import print_function

import sys
import time
import requests

import hal

use_linuxcnc = True


def loop(h, f, ip='192.168.1.116'):
    cmds = { 'dir-listing': 'http://{}/cgi-bin/storageInfo?mmcblk1p1'.format(ip),
             'start-recording': 'http://{}/control/startRecording'.format(ip),
             'stop-recording': 'http://{}/control/stopRecording'.format(ip) }

    recording = False
    pcmd = None
    while True:
        cmd = None

        enable = h['enable']
        if h['trigger-stop']:
            if recording:
                cmd = 'stop'
        else:
            if enable:
                cmd = 'enable'
            else:
                cmd = 'disable'

        if cmd and pcmd != cmd:
             print('{:.6f},{}'.format(time.time(), cmd), file=f)
             if cmd == 'stop':
                 # Continue recording 100ms after trigger
                 time.sleep(.100)
                 print('{:.6f},{}'.format(time.time(), 'fullstop'), file=f)
             try:
                 if cmd == 'enable':
                     post = requests.post(cmds['start-recording'], json = {})
                     recording = True
                 elif cmd in ('stop', 'disable'):
                     post = requests.post(cmds['stop-recording'])
                     recording = False

                     post = requests.get(cmds['dir-listing'])
                     print(time.time(), 'chronos contents:', post.json())
                 h['recording'] = recording
             except requests.exceptions.ConnectionError:
                 h['recording'] = False
                 print('Warning: Chronos camera not responding, disabling')
                 print('{:.6f},{}'.format(time.time(), 'error'), file=f)

             f.flush()
             pcmd = cmd

        time.sleep(.01)


def main():
    if use_linuxcnc:
       h = hal.component('chronos_camera')
       h.newpin('enable', hal.HAL_BIT, hal.HAL_IN)
       h.newpin('trigger-stop', hal.HAL_BIT, hal.HAL_IN)
       h.newpin('recording', hal.HAL_BIT, hal.HAL_OUT)
       h['recording'] = False
       h.ready()
    else:
       h = { 'enable': False,
             'trigger-stop': False,
             'recording': False }

    try:
        fn = 'chronos.log'
        with open(fn, 'a') as f:
            loop(h, f)
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    main()
